version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_DB: blaudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - blau-data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blau-spring-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    #environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      #SPRING_DATASOURCE_USERNAME: myuser
      #SPRING_DATASOURCE_PASSWORD: mypassword

volumes:
  blau-data:

